interface Wine {
    id: string;
    name: string;
    price: number;
    category: string;
}

interface Shop {
    id: string;
    name: string;
    adminId: string;
}

export const sampleWinesData: Wine[] = [
    { id: '1', name: '100 Pipers 12y', price: 2970, category: 'Whisky' },
    { id: '2', name: '100 Pipers 8Y', price: 2880, category: 'Whisky' },
    { id: '3', name: '100 Pipers Nips', price: 540, category: 'Whisky' },
    { id: '4', name: '100 Pipers Pints', price: 1080, category: 'Whisky' },
    { id: '5', name: '100 Pipres Qrs', price: 2160, category: 'Whisky' },
    { id: '6', name: '8 Pm Whisky Nips', price: 220, category: 'Whisky' },
    { id: '7', name: '8 Pm Whisky Pints', price: 440, category: 'Whisky' },
    { id: '8', name: '8 Pm Whisky Qts', price: 880, category: 'Whisky' },
    { id: '9', name: '8 Pm 90 Ml', price: 120, category: 'Whisky' },
    { id: '10', name: 'Absoult Vodka Qts', price: 2470, category: 'Vodka' },
    { id: '11', name: 'All Season   Nips', price: 280, category: 'Brandy' },
    { id: '12', name: 'All Season Pints', price: 560, category: 'Brandy' },
    { id: '13', name: 'Allseason Qts', price: 1120, category: 'Brandy' },
    { id: '14', name: 'Antiquity Blue Nips', price: 360, category: 'Whisky' },
    { id: '15', name: 'Antiquity Blue Pints', price: 730, category: 'Whisky' },
    { id: '16', name: 'Antiquity Blue Qts', price: 1450, category: 'Whisky' },
    { id: '17', name: 'Bakardi  Rum Qts', price: 1320, category: 'Rum' },
    { id: '18', name: 'Ballantines Nips', price: 680, category: 'Whisky' },
    { id: '19', name: 'Ballantines Pints', price: 1360, category: 'Whisky' },
    { id: '20', name: 'Ballantines Qts', price: 2720, category: 'Whisky' },
    { id: '21', name: 'Black Dog 12  Qts', price: 3040, category: 'Whisky' },
    { id: '22', name: 'Black Dog Nips', price: 540, category: 'Whisky' },
    { id: '23', name: 'Black Dog Pints', price: 1090, category: 'Whisky' },
    { id: '24', name: 'Black Dog Qts', price: 2160, category: 'Whisky' },
    { id: '25', name: 'Black Lable Qts', price: 4770, category: 'Whisky' },
    { id: '26', name: 'Black & White Nips', price: 520, category: 'Whisky' },
    { id: '27', name: 'Black & White Pints', price: 1050, category: 'Whisky' },
    { id: '28', name: 'Black & White Qts', price: 2080, category: 'Whisky' },
    { id: '29', name: 'Brezer', price: 130, category: 'Beer' },
    { id: '30', name: 'Brezer Gold', price: 150, category: 'Beer' },
    { id: '31', name: 'B S P Reserve 90 ml', price: 210, category: 'Whisky' },
    { id: '32', name: 'B S P Reserve NIps', price: 390, category: 'Whisky' },
    { id: '33', name: 'B S P Reserve Pints', price: 780, category: 'Whisky' },
    { id: '34', name: 'B S P Reserve Qts', price: 1560, category: 'Whisky' },
    { id: '35', name: 'B S P 2000ML', price: 3560, category: 'Whisky' },
    { id: '36', name: 'B S P 1000 ML', price: 1790, category: 'Whisky' },
    { id: '37', name: 'B S Pride 90 ml', price: 180, category: 'Whisky' },
    { id: '38', name: 'B S Pride Nips', price: 340, category: 'Whisky' },
    { id: '39', name: 'B S Pride Pints', price: 680, category: 'Whisky' },
    { id: '40', name: 'B S Pride Qts', price: 1360, category: 'Whisky' },
    { id: '41', name: 'Budweiser Stroing', price: 260, category: 'Beer' },
    { id: '42', name: 'Bud Magnum Tin', price: 190, category: 'Beer' },
    { id: '43', name: 'Budwiser', price: 250, category: 'Beer' },
    { id: '44', name: 'Budwiser Tin', price: 190, category: 'Beer' },
    { id: '45', name: 'Carona Beer', price: 250, category: 'Beer' },
    { id: '46', name: 'Cheep 1 Ltr', price: 560, category: 'Brandy' },
    { id: '47', name: 'Cheep Nips', price: 110, category: 'Brandy' },
    { id: '48', name: 'Chivas  18 Y Qts', price: 9030, category: 'Whisky' },
    { id: '49', name: 'Chivas  12 Y Qts', price: 4580, category: 'Whisky' },
    { id: '50', name: 'CNB Nips', price: 220, category: 'Brandy' },
    { id: '51', name: 'CNB Pints', price: 440, category: 'Brandy' },
    { id: '52', name: 'CNB Qts', price: 880, category: 'Brandy' },
    { id: '53', name: 'CNB Green Qts', price: 1280, category: 'Brandy' },
    { id: '54', name: 'Dewars White Nips', price: 580, category: 'Whisky' },
    { id: '55', name: 'Dewars White Lable', price: 2320, category: 'Whisky' },
    { id: '56', name: 'Elite Shiraz Nips', price: 300, category: 'Wine' },
    { id: '57', name: 'Elite Shiraz Pints', price: 600, category: 'Wine' },
    { id: '58', name: 'Elite Shiraz Qts', price: 1200, category: 'Wine' },
    { id: '59', name: 'Golfer Shot Qts', price: 1360, category: 'Vodka' },
    { id: '60', name: 'Green Deer  ', price: 180, category: 'Beer' },
    { id: '61', name: 'Hay 5000 Beer', price: 190, category: 'Beer' },
    { id: '62', name: 'Hob Sons Qts', price: 2120, category: 'Whisky' },
    { id: '63', name: 'IB 1000 ml', price: 1010, category: 'Whisky' },
    { id: '64', name: 'I B Nips', price: 190, category: 'Whisky' },
    { id: '65', name: 'I B Pints', price: 380, category: 'Whisky' },
    { id: '66', name: 'I B Qts', price: 760, category: 'Whisky' },
    { id: '67', name: 'I B 90 ml', price: 100, category: 'Whisky' },
    { id: '68', name: 'Iconiq Nips', price: 190, category: 'Whisky' },
    { id: '69', name: 'Iconiq Pints', price: 380, category: 'Whisky' },
    { id: '70', name: 'Iconiq Qts', price: 760, category: 'Whisky' },
    { id: '71', name: 'Iconiq 90 Ml', price: 100, category: 'Whisky' },
    { id: '72', name: 'J and B Whisky', price: 2640, category: 'Whisky' },
    { id: '73', name: 'Johony Blend ', price: 3880, category: 'Whisky' },
    { id: '74', name: 'Jumpson Qts', price: 2760, category: 'Whisky' },
    { id: '75', name: 'Jumpson 200 ml', price: 770, category: 'Whisky' },
    { id: '76', name: 'Henken Lager', price: 270, category: 'Beer' },
    { id: '77', name: 'K F Lager 650 ML', price: 180, category: 'Beer' },
    { id: '78', name: 'K F Strong 650 Ml', price: 190, category: 'Beer' },
    { id: '79', name: 'K F Ultra', price: 250, category: 'Beer' },
    { id: '80', name: 'Kf Ultra Max 650 ml', price: 260, category: 'Beer' },
    { id: '81', name: 'K Out 650 Ml', price: 190, category: 'Beer' },
    { id: '82', name: 'Kyron Brandy Nips', price: 320, category: 'Brandy' },
    { id: '83', name: 'Kyron Brandy Pints', price: 640, category: 'Brandy' },
    { id: '84', name: 'Kyron Brandy Qts', price: 1280, category: 'Brandy' },
    { id: '85', name: 'Legacy nips', price: 390, category: 'Whisky' },
    { id: '86', name: 'Legacy Pints', price: 780, category: 'Whisky' },
    { id: '87', name: 'Legacy Qts', price: 1560, category: 'Whisky' },
    { id: '88', name: 'Lyka Wine Nips', price: 220, category: 'Wine' },
    { id: '89', name: 'Lyka Wine Pints', price: 440, category: 'Wine' },
    { id: '90', name: 'Lyka Wine Qts', price: 880, category: 'Wine' },
    { id: '91', name: 'M M Vodka Nips', price: 210, category: 'Vodka' },
    { id: '92', name: 'M M Vodka Pints', price: 420, category: 'Vodka' },
    { id: '93', name: 'M M Vodka Qts', price: 840, category: 'Vodka' },
    { id: '94', name: 'Majic P Wine Nips', price: 160, category: 'Wine' },
    { id: '95', name: 'Majic P Wine Pints', price: 320, category: 'Wine' },
    { id: '96', name: 'Majic P Wine Qts', price: 640, category: 'Wine' },
    { id: '97', name: 'MCP Nips', price: 210, category: 'Whisky' },
    { id: '98', name: 'M C P Pints', price: 420, category: 'Whisky' },
    { id: '99', name: 'M C P Qts', price: 840, category: 'Whisky' },
    { id: '100', name: 'Mc W 1000 Ml', price: 1010, category: 'Whisky' },
    { id: '101', name: 'M C W Nips', price: 190, category: 'Whisky' },
    { id: '102', name: 'M C W Pints', price: 380, category: 'Whisky' },
    { id: '103', name: 'M C W Qts', price: 760, category: 'Whisky' },
    { id: '104', name: 'M C W 90 Ml', price: 100, category: 'Whisky' },
    { id: '105', name: 'M H B 2 Lits', price: 2020, category: 'Whisky' },
    { id: '106', name: 'M H B 1 Lits', price: 1010, category: 'Whisky' },
    { id: '107', name: 'M H B Nips', price: 180, category: 'Whisky' },
    { id: '108', name: 'M H B Pints', price: 370, category: 'Whisky' },
    { id: '109', name: 'M H B Qts', price: 730, category: 'Whisky' },
    { id: '110', name: 'M H B 90 Ml', price: 100, category: 'Whisky' },
    { id: '111', name: 'MHB Orenge Nips', price: 220, category: 'Whisky' },
    { id: '112', name: 'MHB Orenge Pints', price: 440, category: 'Whisky' },
    { id: '113', name: 'MHB Orenge Qts', price: 880, category: 'Whisky' },
    { id: '114', name: 'M H W Nips', price: 230, category: 'Whisky' },
    { id: '115', name: 'M H W Pints', price: 450, category: 'Whisky' },
    { id: '116', name: 'M H W Qts', price: 920, category: 'Whisky' },
    { id: '117', name: 'Morphose Nips', price: 310, category: 'Whisky' },
    { id: '118', name: 'Morphose Pints', price: 620, category: 'Whisky' },
    { id: '119', name: 'Morphose Qts', price: 1240, category: 'Whisky' },
    { id: '120', name: 'O A B Nips', price: 140, category: 'Whisky' },
    { id: '121', name: 'O A B Qts', price: 560, category: 'Whisky' },
    { id: '122', name: 'O A B 90ML', price: 80, category: 'Whisky' },
    { id: '123', name: 'O A B 1000 ml', price: 760, category: 'Whisky' },
    { id: '124', name: 'Oaken Glow  Qts', price: 1280, category: 'Whisky' },
    { id: '125', name: 'Oaken Glow  Nips', price: 320, category: 'Whisky' },
    { id: '126', name: 'O C W Nips', price: 160, category: 'Whisky' },
    { id: '127', name: 'O C W Pints', price: 320, category: 'Whisky' },
    { id: '128', name: 'O C W Qts', price: 640, category: 'Whisky' },
    { id: '129', name: 'O C W 90 Ml', price: 90, category: 'Whisky' },
    { id: '130', name: 'O C W Blue Nips', price: 190, category: 'Whisky' },
    { id: '131', name: 'O C W Blue Pints', price: 380, category: 'Whisky' },
    { id: '132', name: 'O C W Blue Qts', price: 760, category: 'Whisky' },
    { id: '133', name: 'O C W Blue 90ml', price: 100, category: 'Whisky' },
    { id: '134', name: 'Oksmith G Nips', price: 370, category: 'Whisky' },
    { id: '135', name: 'Oksmith G Pints', price: 740, category: 'Whisky' },
    { id: '136', name: 'Oksmith G Qts', price: 1480, category: 'Whisky' },
    { id: '137', name: 'Oksmith S Nips', price: 260, category: 'Whisky' },
    { id: '138', name: 'Oksmith S Pints', price: 520, category: 'Whisky' },
    { id: '139', name: 'Oksmith S Qts', price: 1040, category: 'Whisky' },
    { id: '140', name: 'Old Munk rum Nips', price: 190, category: 'Rum' },
    { id: '141', name: 'Old Munk rum Pints', price: 380, category: 'Rum' },
    { id: '142', name: 'Old Munk rum Qts', price: 760, category: 'Rum' },
    { id: '143', name: 'Opera Wine Nips', price: 220, category: 'Wine' },
    { id: '144', name: 'Opera Wine Pints', price: 440, category: 'Wine' },
    { id: '145', name: 'Opera Wine Qts', price: 880, category: 'Wine' },
    { id: '146', name: 'R C Beer 650 Ml', price: 180, category: 'Beer' },
    { id: '147', name: 'Rc Blue 90 ML', price: 120, category: 'Whisky' },
    { id: '148', name: 'Rc Blended Nips', price: 220, category: 'Whisky' },
    { id: '149', name: 'Rc Blended Pints', price: 440, category: 'Whisky' },
    { id: '150', name: 'Rc Blended Qts', price: 880, category: 'Whisky' },
    { id: '151', name: 'Rcw American  Nips', price: 340, category: 'Whisky' },
    { id: '152', name: 'Rcw American  Pints', price: 680, category: 'Whisky' },
    { id: '153', name: 'Rcw American Qts', price: 1360, category: 'Whisky' },
    { id: '154', name: 'R C Whisky 2 Lits', price: 2960, category: 'Whisky' },
    { id: '155', name: 'R C Whisky 1 Lits', price: 1480, category: 'Whisky' },
    { id: '156', name: 'R C Whisky Nips', price: 300, category: 'Whisky' },
    { id: '157', name: 'R C Whisky Pints', price: 600, category: 'Whisky' },
    { id: '158', name: 'R C Whisky Qts', price: 1200, category: 'Whisky' },
    { id: '159', name: 'R C Whisky 90 Ml', price: 160, category: 'Whisky' },
    { id: '160', name: 'Red Lable Qts', price: 2610, category: 'Whisky' },
    { id: '161', name: 'Royal Green 90 ml', price: 120, category: 'Whisky' },
    { id: '162', name: 'Royal Green Nips', price: 220, category: 'Whisky' },
    { id: '163', name: 'Royal Green Pints', price: 440, category: 'Whisky' },
    { id: '164', name: 'Royal Green Qts', price: 880, category: 'Whisky' },
    { id: '165', name: 'Rock Ford Qts', price: 1460, category: 'Whisky' },
    { id: '166', name: 'Rock Ford Pints', price: 730, category: 'Whisky' },
    { id: '167', name: 'Rock Ford Nips', price: 360, category: 'Whisky' },
    { id: '168', name: 'R Stage 2 Lits', price: 2340, category: 'Whisky' },
    { id: '169', name: 'R Stage 1 Lits', price: 1180, category: 'Whisky' },
    { id: '170', name: 'R Stage Nips', price: 220, category: 'Whisky' },
    { id: '171', name: 'R Stage Pints', price: 440, category: 'Whisky' },
    { id: '172', name: 'R Stage Qts', price: 880, category: 'Whisky' },
    { id: '173', name: 'R Stage 90 Ml', price: 120, category: 'Whisky' },
    { id: '174', name: 'Signature 2 lits', price: 3510, category: 'Whisky' },
    { id: '175', name: 'Signature  1 lits', price: 1750, category: 'Whisky' },
    { id: '176', name: 'Signature Nips', price: 340, category: 'Whisky' },
    { id: '177', name: 'Signature  Pints', price: 680, category: 'Whisky' },
    { id: '178', name: 'Signature Qts', price: 1360, category: 'Whisky' },
    { id: '179', name: 'Signature 90 ml', price: 180, category: 'Whisky' },
    { id: '180', name: 'Smirnoff Nips', price: 310, category: 'Vodka' },
    { id: '181', name: 'Smirnoff Pints', price: 620, category: 'Vodka' },
    { id: '182', name: 'Smirnoff Qts', price: 1240, category: 'Vodka' },
    { id: '183', name: 'Sterling B10 Nibs', price: 350, category: 'Whisky' },
    { id: '184', name: 'Sterling B10 Pints', price: 700, category: 'Whisky' },
    { id: '185', name: 'Sterling B 10 Qts', price: 1400, category: 'Whisky' },
    { id: '186', name: 'Sterling B7 Nibs', price: 220, category: 'Whisky' },
    { id: '187', name: 'Sterling B7 Pints', price: 440, category: 'Whisky' },
    { id: '188', name: 'Sterling B7 Qts', price: 880, category: 'Whisky' },
    { id: '189', name: 'Sterling B7 90ml', price: 120, category: 'Whisky' },
    { id: '190', name: 'Sula Red Wine Nips', price: 300, category: 'Wine' },
    { id: '191', name: 'Sula Red Wine Pints', price: 600, category: 'Wine' },
    { id: '192', name: 'Sula Red Wine Qts', price: 1200, category: 'Wine' },
    { id: '193', name: 'P Stcoh Qts', price: 1450, category: 'Whisky' },
    { id: '194', name: 'Teachers 50', price: 3200, category: 'Whisky' },
    { id: '195', name: 'Teachers Nips', price: 580, category: 'Whisky' },
    { id: '196', name: 'Teachers Pints', price: 1160, category: 'Whisky' },
    { id: '197', name: 'Teachers Qts', price: 2320, category: 'Whisky' },
    { id: '198', name: 'The Glenveet 12y ', price: 7100, category: 'Whisky' },
    { id: '199', name: 'Thalisker Qts', price: 6590, category: 'Whisky' },
    { id: '200', name: 'Twntey One Plus Qts', price: 1450, category: 'Whisky' },
    { id: '201', name: 'Vat 69 Nips', price: 500, category: 'Whisky' },
    { id: '202', name: 'Vat 69 Pints', price: 1010, category: 'Whisky' },
    { id: '203', name: 'Vat 69 Qts', price: 2000, category: 'Whisky' },
    { id: '204', name: 'William Law son Qts', price: 2200, category: 'Whisky' }
];


export const initialShopsData: Shop[] = [

    { id: 'shop_1', name: 'Downtown Wine Shop', adminId: 'admin_1' },
    { id: 'shop_2', name: 'Northside Liquor Store', adminId: 'admin_2' },
    { id: 'shop_3', name: 'Eastview Wine Mart', adminId: 'admin_3' },
    { id: 'shop_4', name: 'Westgate Spirits', adminId: 'admin_4' },
    { id: 'shop_5', name: 'Central Plaza Wines', adminId: 'admin_5' },
    { id: 'shop_6', name: 'Riverside Liquor Shop', adminId: 'admin_6' },
    { id: 'shop_7', name: 'Hillside Wine Store', adminId: 'admin_7' },
    { id: 'shop_8', name: 'Market Street Wines', adminId: 'admin_8' },
    { id: 'shop_9', name: 'Garden City Liquor', adminId: 'admin_9' },
    { id: 'shop_10', name: 'Lakeside Wine Shop', adminId: 'admin_10' },
    { id: 'shop_11', name: 'Parkview Spirits', adminId: 'admin_11' },
    { id: 'shop_12', name: 'Junction Wine Mart', adminId: 'admin_12' },
    { id: 'shop_13', name: 'Broadway Liquor Store', adminId: 'admin_13' },
    { id: 'shop_14', name: 'Sunset Wine Shop', adminId: 'admin_14' },
    { id: 'shop_15', name: 'Sunrise Spirits', adminId: 'admin_15' },
    { id: 'shop_16', name: 'Valley Wine Store', adminId: 'admin_16' },
    { id: 'shop_17', name: 'Mountain View Liquor', adminId: 'admin_17' },
    { id: 'shop_18', name: 'Ocean Breeze Wines', adminId: 'admin_18' },
    { id: 'shop_19', name: 'Forest Grove Wine Shop', adminId: 'admin_19' },
    { id: 'shop_20', name: 'Meadow Spirits', adminId: 'admin_20' },
    { id: 'shop_21', name: 'Crystal Wine Mart', adminId: 'admin_21' },
    { id: 'shop_22', name: 'Golden Gate Liquor', adminId: 'admin_22' },
    { id: 'shop_23', name: 'Silver Creek Wine Shop', adminId: 'admin_23' },
    { id: 'shop_24', name: 'Maple Street Spirits', adminId: 'admin_24' },
    { id: 'shop_25', name: 'Oak Avenue Wines', adminId: 'admin_25' },
    { id: 'shop_26', name: 'Pine Ridge Liquor Store', adminId: 'admin_26' },
    { id: 'shop_27', name: 'Cedar Plaza Wine Shop', adminId: 'admin_27' },
    { id: 'shop_28', name: 'Elm Street Spirits', adminId: 'admin_28' },
    { id: 'shop_29', name: 'Birch Lane Wine Mart', adminId: 'admin_29' },
    { id: 'shop_30', name: 'Willow Way Liquor', adminId: 'admin_30' },
];
